### ISSUE TITLE
Double release

### ISSUE THREAD

**Issue by victorsempere** [Mazoise/42TESTERS-GNL#1]
Maybe I'm wrong but the gnl_tester.c seems to be doing double free.
Line:48
And seems that maybe it's happening at some places after this line

**Comment by Mazoise** [comment]
You don't have a problem on the first test because I keep each address for line in a table and free everything at the end of the test. I don't double free line at any point in the test. There's probably somewhere in your code where you either free line when you shouldn't or you don't malloc line each time you should. If you're in 42 paris you can come see me or send me your code if you want me to take a look.

**Comment by victorsempere** [comment]
I had a problem not allocating memory for an empty line. Thanks. Your test
worked ok
